<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_62b200ce716a3',
	'title' => 'Casas',
	'fields' => array(
		array(
			'key' => 'field_62bb64fa1ea09',
			'label' => 'Imagen Principal',
			'name' => 'imagen_principal',
			'type' => 'image',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => 600,
			'min_height' => 600,
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_62b213d6c2169',
			'label' => 'Precio',
			'name' => 'precio',
			'type' => 'number',
			'instructions' => 'Introduce el precio de la propiedad',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_62b2021f19c30',
			'label' => 'Descripción corta',
			'name' => 'descripcion-corta',
			'type' => 'textarea',
			'instructions' => 'En este espacio se puede escribir una descripción breve de la casa.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => 250,
			'rows' => 4,
			'new_lines' => '',
		),
		array(
			'key' => 'field_62b208f78b72c',
			'label' => 'Descripción',
			'name' => 'descripcion',
			'type' => 'textarea',
			'instructions' => 'Aquí se puede poner a detalle las características de la construcción, en especial si los campos siguientes no ofrecen opciones para peculiaridades de la propiedad.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'br',
		),
		array(
			'key' => 'field_62b2076d619b0',
			'label' => 'Colonia',
			'name' => 'colonia',
			'type' => 'text',
			'instructions' => 'Introducir la colonia del inmueble.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_62b2014719c25',
			'label' => 'Calle',
			'name' => 'calle',
			'type' => 'text',
			'instructions' => 'Introduce la calle donde se encuentra la casa, con numero',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_62b207d1619b1',
			'label' => 'Código postal',
			'name' => 'codigo_postal',
			'type' => 'number',
			'instructions' => 'Introduce el código postal',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_62b2015d19c26',
			'label' => 'Estatus',
			'name' => 'estatus',
			'type' => 'radio',
			'instructions' => 'Selecciona el estatus de la casa',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'En Venta' => 'En Venta',
				'Pre Venta' => 'Pre Venta',
				'Vendida' => 'Vendida',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_62b2016c19c27',
			'label' => 'Tipo terreno',
			'name' => 'tipo_terreno',
			'type' => 'select',
			'instructions' => 'Selecciona si el terreno es regular o irregular',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Regular' => 'Regular',
				'Irregular' => 'Irregular',
			),
			'default_value' => 'regular',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_62b20808937a4',
			'label' => 'Tamaño de terreno',
			'name' => 'tamano-terreno',
			'type' => 'text',
			'instructions' => 'Escribe el área del terreno',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_62b2017519c28',
			'label' => 'Área de construcción',
			'name' => 'area_de_construccion',
			'type' => 'number',
			'instructions' => 'Escribe el área de construcción en metros cuadrados',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_62b2018519c29',
			'label' => 'Plantas',
			'name' => 'plantas',
			'type' => 'number',
			'instructions' => 'Introduce el número de plantas que tiene la propiedad.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_62b2018c19c2a',
			'label' => 'Recamaras',
			'name' => 'recamaras',
			'type' => 'number',
			'instructions' => 'Escribe la cantidad de cuartos que tiene la casa.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_62b2019819c2b',
			'label' => 'Baños',
			'name' => 'banos',
			'type' => 'number',
			'instructions' => 'Hay que definir cuantos baños tiene la construcción.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_62b201ef19c2c',
			'label' => 'Medios Baños',
			'name' => 'medio_bano',
			'type' => 'number',
			'instructions' => 'Solo en caso de tener medios baños, introducir cuantos tiene la casa.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_62b201f719c2d',
			'label' => 'Cochera',
			'name' => 'cochera',
			'type' => 'text',
			'instructions' => 'En caso de tener cochera, escribir cuántos automóviles caben en ella.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_62b2020019c2e',
			'label' => 'Cuarto de Lavado',
			'name' => 'cuarto_de_lavado',
			'type' => 'number',
			'instructions' => 'En caso de contar con cuarto de lavado, introducir la cantidad de la casa.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_62b2020919c2f',
			'label' => 'Sala de TV',
			'name' => 'sala_de_tv',
			'type' => 'number',
			'instructions' => 'En caso de tener un cuarto de tv independiente introducir su cantidad.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_62b2147e4f251',
			'label' => 'Balcon',
			'name' => 'balcon',
			'type' => 'number',
			'instructions' => 'En caso de tener balcón, la cantidad que la casa tiene.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_62b214c84f252',
			'label' => 'Jardin',
			'name' => 'jardin',
			'type' => 'radio',
			'instructions' => 'Selecciona si la casa tiene jardín o no.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Con jardín' => 'Con jardín',
				'Sin jardín' => 'Sin jardín',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_62b2023919c31',
			'label' => 'Ubicación',
			'name' => 'ubicacion',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_62bb45e583062',
			'label' => 'Mapa',
			'name' => 'mapa',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_62bb4b68a103a',
			'label' => 'imagen-01',
			'name' => 'imagen-01',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => 600,
			'min_height' => 300,
			'min_size' => '',
			'max_width' => 600,
			'max_height' => 300,
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_62bb4ba6a103b',
			'label' => 'imagen-02',
			'name' => 'imagen-02',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => 600,
			'min_height' => 300,
			'min_size' => '',
			'max_width' => 600,
			'max_height' => 300,
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_62bb4bbda103c',
			'label' => 'imagen-03',
			'name' => 'imagen-03',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => 600,
			'min_height' => 300,
			'min_size' => '',
			'max_width' => 600,
			'max_height' => 300,
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_62bb4bc7a103d',
			'label' => 'imagen-04',
			'name' => 'imagen-04',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => 600,
			'min_height' => 300,
			'min_size' => '',
			'max_width' => 600,
			'max_height' => 300,
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_62bb4bd0a103e',
			'label' => 'imagen-05',
			'name' => 'imagen-05',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => 600,
			'min_height' => 300,
			'min_size' => '',
			'max_width' => 600,
			'max_height' => 300,
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'casas',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
		1 => 'excerpt',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
));

endif;		